#!/usr/bin/env bash

set -eu

repo_abs=$(readlink -f $0 | xargs dirname) 
repo=$(realpath --relative-to="${HOME}" ${repo_abs})

printf "Installing dotfiles from ${repo} (${repo_abs})...\n"

linkfromhome() {
  ln -sfv $repo/$1 ~/
}

ln -sfv $repo_abs/bin ~/bin/dotfiles
linkfromhome .bmfiles
linkfromhome .bmdirs
linkfromhome .ackrc
linkfromhome .i3
linkfromhome .spacemacs.d
