#!/usr/bin/env bash

set -eu

repo_abs=$(readlink -f $0 | xargs dirname)
repo=$(realpath --relative-to="${HOME}" ${repo_abs})

linkfromhome() {
  ln -sfv $repo/$1 ~/
}

printf "Installing packages...(may ask for password)\n"

sudo aptitude install \
     ruby-color \
     rxvt-unicode \
     i3-wm \
     i3blocks \
     emacs \
     inotify-tools \
     libnotify-bin \
     entr \
     translate \
     redshift-gtk \
     feh

printf "Installing dotfiles from ${repo} (${repo_abs})...\n"

ln -sfv $repo_abs/bin ~/bin
ln -sfv $repo_abs/.config/ranger ~/.config/
ln -sfv $repo_abs/.config/dunst ~/.config/
linkfromhome .bmfiles
linkfromhome .bmdirs
linkfromhome .ackrc
linkfromhome .Xresources
linkfromhome .i3
linkfromhome .agignore
linkfromhome .profile
linkfromhome bash/.bashrc
linkfromhome .spacemacs.d
linkfromhome .xinitrc

if [[ -d ~/bin/git-prompt ]]
then
    printf "git-prompt already installed\n"
else
    git clone git@github.com:niklas/git-prompt.git ~/bin/git-prompt
fi
